// French card data for the game - 99 Question Cards (Adult Content)
export const QUESTION_CARDS = [
  { id: 1, text: "Ma première fois, c'était avec ___.", blanks: 1, category: "adult" },
  { id: 2, text: "Quand je pense à maman, je bande à cause de ___.", blanks: 1, category: "adult" },
  { id: 3, text: "Papy est mort comme il a vécu : avec _____ coincé dans le rectum.", blanks: 1, category: "adult" },
  { id: 4, text: "Ce que j'ai trouvé dans mon anus ce matin : ___.", blanks: 1, category: "adult" },
  { id: 5, text: "En enfer, le châtiment éternel, c'est ___.", blanks: 1, category: "adult" },
  { id: 6, text: "À Noël, mamie m'a offert ___.", blanks: 1, category: "adult" },
  { id: 7, text: "Le prêtre a glissé sur _____ pendant la messe.", blanks: 1, category: "adult" },
  { id: 8, text: "Ma sex-tape a fuité. Elle s'appelle ___.", blanks: 1, category: "adult" },
  { id: 9, text: "Si je deviens président, je légaliserai ___.", blanks: 1, category: "adult" },
  { id: 10, text: "Mon kink secret ? ___.", blanks: 1, category: "adult" },
  { id: 11, text: "Le seul remède contre ma dépression : ___.", blanks: 1, category: "adult" },
  { id: 12, text: "À la maternelle, j'ai appris l'existence de ___.", blanks: 1, category: "adult" },
  { id: 13, text: "Mon chat m'a surpris en train de ___.", blanks: 1, category: "adult" },
  { id: 14, text: "Tinder m'a matché avec ___.", blanks: 1, category: "adult" },
  { id: 15, text: "Les experts ont découvert que le Covid était causé par ___.", blanks: 1, category: "adult" },
  { id: 16, text: "Si Dieu existe, pourquoi a-t-il créé _____ ?", blanks: 1, category: "adult" },
  { id: 17, text: "Je peux tolérer beaucoup, mais pas ___.", blanks: 1, category: "adult" },
  { id: 18, text: "Mon boss m'a licencié après avoir vu ___.", blanks: 1, category: "adult" },
  { id: 19, text: "Rêve récurrent : moi, tout nu, poursuivi par ___.", blanks: 1, category: "adult" },
  { id: 20, text: "Le menu du jour : steak, frites et ___.", blanks: 1, category: "adult" },
  { id: 21, text: "J'ai insulté mon patron avec ___.", blanks: 1, category: "adult" },
  { id: 22, text: "Les experts confirment : _____ provoque le cancer du bonheur.", blanks: 1, category: "adult" },
  { id: 23, text: "J'ai perdu ma virginité avec _____ dans un confessionnal.", blanks: 1, category: "adult" },
  { id: 24, text: "Si j'étais un super-héros, mon pouvoir serait ___.", blanks: 1, category: "adult" },
  { id: 25, text: "Nouvel ingrédient dans les Kinder Surprise : ___.", blanks: 1, category: "adult" },
  { id: 26, text: "J'ai été banni d'Instagram pour avoir posté ___.", blanks: 1, category: "adult" },
  { id: 27, text: "Mon voisin cache _____ dans son congélateur.", blanks: 1, category: "adult" },
  { id: 28, text: "Une nouvelle religion est née autour de ___.", blanks: 1, category: "adult" },
  { id: 29, text: "Mon psy m'a conseillé de parler à ___.", blanks: 1, category: "adult" },
  { id: 30, text: "On m'a surpris en train de caresser _____ dans le métro.", blanks: 1, category: "adult" },
  { id: 31, text: "Un bon mariage repose sur ___.", blanks: 1, category: "adult" },
  { id: 32, text: "L'arme secrète des russes pendant la guerre : ___.", blanks: 1, category: "adult" },
  { id: 33, text: "Quand la honte devient palpable, c'est souvent à cause de ___.", blanks: 1, category: "adult" },
  { id: 34, text: "Mon prochain tatouage : un portrait de _____ sur mes fesses.", blanks: 1, category: "adult" },
  { id: 35, text: "Ce que j'apporte toujours à un enterrement : ___.", blanks: 1, category: "adult" },
  { id: 36, text: "J'ai découvert que mon ex était accro à ___.", blanks: 1, category: "adult" },
  { id: 37, text: "Un bon petit déjeuner commence toujours avec ___.", blanks: 1, category: "adult" },
  { id: 38, text: "Les aliens ont fui la Terre après avoir vu ___.", blanks: 1, category: "adult" },
  { id: 39, text: "Dans la secte de Jean-Michel, on vénère ___.", blanks: 1, category: "adult" },
  { id: 40, text: "Ce qui m'empêche de dormir : ___.", blanks: 1, category: "adult" },
  { id: 41, text: "Je suis allergique à _____, sauf quand je suis seul(e).", blanks: 1, category: "adult" },
  { id: 42, text: "Le truc qu'on ne devrait jamais mettre dans un micro-ondes : ___.", blanks: 1, category: "adult" },
  { id: 43, text: "Nouvel ingrédient secret du Coca-Cola : ___.", blanks: 1, category: "adult" },
  { id: 44, text: "Ce que je cache dans ma boîte à gants : ___.", blanks: 1, category: "adult" },
  { id: 45, text: "La vraie raison de mon renvoi : ___.", blanks: 1, category: "adult" },
  { id: 46, text: "Dieu aurait dû arrêter après avoir inventé ___.", blanks: 1, category: "adult" },
  { id: 47, text: "Ce qui est plus addictif que la cocaïne : ___.", blanks: 1, category: "adult" },
  { id: 48, text: "Le film interdit de Disney : ___.", blanks: 1, category: "adult" },
  { id: 49, text: "Raison officielle de ma dernière garde à vue : ___.", blanks: 1, category: "adult" },
  { id: 50, text: "Le remède miracle pour bander : ___.", blanks: 1, category: "adult" },
  { id: 51, text: "Ce que mon prof a trouvé dans mon sac : ___.", blanks: 1, category: "adult" },
  { id: 52, text: "Je me suis réveillé avec _____ tatoué sur mon front.", blanks: 1, category: "adult" },
  { id: 53, text: "Le truc qui m'a fait rater mon permis : ___.", blanks: 1, category: "adult" },
  { id: 54, text: "J'ai proposé à mon boss une stratégie basée sur ___.", blanks: 1, category: "adult" },
  { id: 55, text: "Les flics m'ont arrêté car j'étais en possession de ___.", blanks: 1, category: "adult" },
  { id: 56, text: "Si je gagnais au Loto, je dépenserais tout dans ___.", blanks: 1, category: "adult" },
  { id: 57, text: "Une réunion d'équipe qui dégénère finit toujours par ___.", blanks: 1, category: "adult" },
  { id: 58, text: "Je pense que mon coloc me trompe avec ___.", blanks: 1, category: "adult" },
  { id: 59, text: "Ce qui devrait remplacer le drapeau français : ___.", blanks: 1, category: "adult" },
  { id: 60, text: "Nouvelle mode sur TikTok : se filmer en train de ___.", blanks: 1, category: "adult" },
  { id: 61, text: "Le meilleur moyen de faire fuir un recruteur : ___.", blanks: 1, category: "adult" },
  { id: 62, text: "Ce que mon chien a vomi ce matin : ___.", blanks: 1, category: "adult" },
  { id: 63, text: "À la maison de retraite, on organise des soirées ___.", blanks: 1, category: "adult" },
  { id: 64, text: "Ce que mon double maléfique adore : ___.", blanks: 1, category: "adult" },
  { id: 65, text: "Je me masturbe toujours en pensant à ___.", blanks: 1, category: "adult" },
  { id: 66, text: "Les courses à Lidl deviennent bizarres quand on ajoute ___.", blanks: 1, category: "adult" },
  { id: 67, text: "Mon prochain business va vendre ___.", blanks: 1, category: "adult" },
  { id: 68, text: "À la cantine, j'ai trouvé _____ dans mon assiette.", blanks: 1, category: "adult" },
  { id: 69, text: "Le pire mot de passe du monde : ___.", blanks: 1, category: "adult" },
  { id: 70, text: "Si mon sexe avait un nom, ce serait ___.", blanks: 1, category: "adult" },
  { id: 71, text: "Je suis entré dans une secte pour ___.", blanks: 1, category: "adult" },
  { id: 72, text: "Je suis tombé amoureux(se) de ___.", blanks: 1, category: "adult" },
  { id: 73, text: "La vraie raison du divorce de mes parents : ___.", blanks: 1, category: "adult" },
  { id: 74, text: "Ce que mon enfant a crié dans l'église : ___.", blanks: 1, category: "adult" },
  { id: 75, text: "La raison pour laquelle j'ai été viré de Pornhub : ___.", blanks: 1, category: "adult" },
  { id: 76, text: "Dans mon testament, j'ai laissé _____ à chacun de mes amis.", blanks: 1, category: "adult" },
  { id: 77, text: "Nouvel aliment végan : ___.", blanks: 1, category: "adult" },
  { id: 78, text: "Ce que je fais toujours après une rupture : ___.", blanks: 1, category: "adult" },
  { id: 79, text: "Le nouveau médicament contre l'ennui : ___.", blanks: 1, category: "adult" },
  { id: 80, text: "Ce que j'ai hurlé pendant l'orgasme : ___.", blanks: 1, category: "adult" },
  { id: 81, text: "L'arme secrète de la police : ___.", blanks: 1, category: "adult" },
  { id: 82, text: "Ma prochaine reconversion : coach en ___.", blanks: 1, category: "adult" },
  { id: 83, text: "Le nouveau challenge dangereux sur Insta : ___.", blanks: 1, category: "adult" },
  { id: 84, text: "Un truc qu'on ne dit jamais pendant une levrette : ___.", blanks: 1, category: "adult" },
  
  // Multi-blank questions
  { id: 85, text: "… et un extincteur.", blanks: 1, category: "adult" },
  { id: 86, text: "Nouvelle tendance sur OnlyFans : _____ et du beurre fondu.", blanks: 1, category: "adult" },
  { id: 87, text: "Raison officielle du divorce : _____ sur la table du salon.", blanks: 1, category: "adult" },
  { id: 88, text: "Nouvelle émission sur Netflix : \"Ma vie avec ___\".", blanks: 1, category: "adult" },
  { id: 89, text: "Ma prochaine sextape inclura _____ et des cris de chèvre.", blanks: 1, category: "adult" },
  { id: 90, text: "La nouvelle politique RH autorise _____ à condition de le filmer.", blanks: 1, category: "adult" },
  { id: 91, text: "Le nouveau slogan du gouvernement : \"_____ pour tous\".", blanks: 1, category: "adult" },
  { id: 92, text: "Nouvelle attraction à Disneyland : _____ la montagne russe.", blanks: 1, category: "adult" },
  { id: 93, text: "Je n'aurais jamais dû essayer _____ avec mes parents dans la pièce.", blanks: 1, category: "adult" },
  { id: 94, text: "Ma sextape préférée s'intitule : \"50 nuances de ___\".", blanks: 1, category: "adult" },
  { id: 95, text: "Ma punchline préférée : \"Va te faire _____ !\"", blanks: 1, category: "adult" },
  { id: 96, text: "Nouvel épisode de Black Mirror : ___.", blanks: 1, category: "adult" },
  { id: 97, text: "Nouvelle appli de rencontre pour amateurs de ___.", blanks: 1, category: "adult" },
  { id: 98, text: "Le nouveau parfum de Dior s'appelle \"_____ Sauvage\".", blanks: 1, category: "adult" },
  { id: 99, text: "Ce que j'écris sur ma tombe : \"Mort par ___\".", blanks: 1, category: "adult" },
  { id: 100, text: "À mon anniversaire, j'ai reçu _____ et la syphilis.", blanks: 1, category: "adult" }
];

// French Answer Cards - 164 Adult Content Cards
export const ANSWER_CARDS = [
  { id: 1, text: "une sextape avec mon jumeau maléfique", category: "adult" },
  { id: 2, text: "un gode usagé signé par ta grand-mère", category: "adult" },
  { id: 3, text: "un pet si humide qu'il devient baptême", category: "adult" },
  { id: 4, text: "le doigt d'honneur d'un bébé mort-né", category: "adult" },
  { id: 5, text: "du lubrifiant goût sardine", category: "adult" },
  { id: 6, text: "une pipe sous une table IKEA bancale", category: "adult" },
  { id: 7, text: "un cunnilingus raté sur une poupée Barbie", category: "adult" },
  { id: 8, text: "une partouze entre zombies décapités", category: "adult" },
  { id: 9, text: "un cri orgasmique pendant l'enterrement de Mémé", category: "adult" },
  { id: 10, text: "la bite de Satan dans un Tupperware", category: "adult" },
  { id: 11, text: "des ongles de pied dans un milkshake", category: "adult" },
  { id: 12, text: "se faire fister avec une main en plâtre", category: "adult" },
  { id: 13, text: "un prêtre lubrifié récitant le Coran", category: "adult" },
  { id: 14, text: "l'urine bénite du Pape François", category: "adult" },
  { id: 15, text: "une omelette faite avec des ovules volés", category: "adult" },
  { id: 16, text: "une quenelle insérée avec amour", category: "adult" },
  { id: 17, text: "un vibromasseur solaire à énergie négative", category: "adult" },
  { id: 18, text: "un PowerPoint érotique sur les MST", category: "adult" },
  { id: 19, text: "un anus tatoué 'liberté, égalité, sodomie'", category: "adult" },
  { id: 20, text: "le moisi entre les orteils de Jésus", category: "adult" },
  { id: 21, text: "des moines qui twerkent en silence", category: "adult" },
  { id: 22, text: "un hamster dans un préservatif à l'envers", category: "adult" },
  { id: 23, text: "la touffe de Kim Jong-un", category: "adult" },
  { id: 24, text: "la moiteur d'un slip de compétition", category: "adult" },
  { id: 25, text: "le cri de détresse d'un clitoris perdu", category: "adult" },
  { id: 26, text: "une poupée gonflable possédée par l'âme de Hitler", category: "adult" },
  { id: 27, text: "une sextape entre un furet et un curé", category: "adult" },
  { id: 28, text: "un cunnilingus à travers un masque chirurgical", category: "adult" },
  { id: 29, text: "des sex-toys sculptés dans du beurre", category: "adult" },
  { id: 30, text: "une levrette sur fond d'hymne national", category: "adult" },
  { id: 31, text: "un pet béni par le Dalaï-Lama", category: "adult" },
  { id: 32, text: "un orgasme provoqué par le son d'une tondeuse", category: "adult" },
  { id: 33, text: "un vibromasseur connecté à la bourse mondiale", category: "adult" },
  { id: 34, text: "des traces de sperme sur une bible de poche", category: "adult" },
  { id: 35, text: "un sex-shop tenu par des jumeaux siamois", category: "adult" },
  { id: 36, text: "un préservatif tricoté par Mamie", category: "adult" },
  { id: 37, text: "une morve sacrée utilisée comme lubrifiant", category: "adult" },
  { id: 38, text: "le fantôme d'un orgasme non terminé", category: "adult" },
  { id: 39, text: "un bukkake au vin chaud", category: "adult" },
  { id: 40, text: "un pet qui sent la trahison", category: "adult" },
  { id: 41, text: "un doigt dans l'oreille de Dieu", category: "adult" },
  { id: 42, text: "une fellation sous acide dans un confessionnal", category: "adult" },
  { id: 43, text: "un urinoir béni par le Pape", category: "adult" },
  { id: 44, text: "un plug anal en forme de Tour Eiffel", category: "adult" },
  { id: 45, text: "un strip-tease de licorne cocaïnée", category: "adult" },
  { id: 46, text: "une bifle cosmique", category: "adult" },
  { id: 47, text: "un vibromasseur avec l'âme de ton ex", category: "adult" },
  { id: 48, text: "un gang-bang végétalien", category: "adult" },
  { id: 49, text: "un prêtre en string fluo", category: "adult" },
  { id: 50, text: "une claque portée avec le cœur (et une tapette à mouche)", category: "adult" },
  { id: 51, text: "des frites trempées dans du lubrifiant", category: "adult" },
  { id: 52, text: "une éjaculation surprise pendant un cours de yoga", category: "adult" },
  { id: 53, text: "un chihuahua en latex gémissant à chaque pénétration", category: "adult" },
  { id: 54, text: "une bouteille de Ricard utilisée comme sextoy", category: "adult" },
  { id: 55, text: "un pénis peint aux couleurs du drapeau belge", category: "adult" },
  { id: 56, text: "un massage prostatique au marteau-piqueur", category: "adult" },
  { id: 57, text: "des préliminaires faits avec une perceuse", category: "adult" },
  { id: 58, text: "un pet coincé entre deux seins bénis", category: "adult" },
  { id: 59, text: "une masturbation collective dans une station-service", category: "adult" },
  { id: 60, text: "le slip sale de Napoléon", category: "adult" },
  { id: 61, text: "une gaufre fourrée au sperme de licorne", category: "adult" },
  { id: 62, text: "un orgasme provoqué par un cri de dauphin", category: "adult" },
  { id: 63, text: "une orgie de mimes silencieux mais sales", category: "adult" },
  { id: 64, text: "une cravache trempée dans du chocolat chaud", category: "adult" },
  { id: 65, text: "un concours de pets vaginaux en direct sur Twitch", category: "adult" },
  { id: 66, text: "un pénis voilé par pudeur religieuse", category: "adult" },
  { id: 67, text: "une sodomie métaphysique", category: "adult" },
  { id: 68, text: "un exorcisme anal à l'eau bénite", category: "adult" },
  { id: 69, text: "un trône en godemichets recyclés", category: "adult" },
  { id: 70, text: "des traces de sperme dans la soupe populaire", category: "adult" },
  { id: 71, text: "un lama qui pratique la fellation tantrique", category: "adult" },
  { id: 72, text: "une sextape tournée avec un drone militaire", category: "adult" },
  { id: 73, text: "une douche dorée dans une cathédrale abandonnée", category: "adult" },
  { id: 74, text: "une bite dessinée dans les nuages", category: "adult" },
  { id: 75, text: "un massage cardiaque fait avec les fesses", category: "adult" },
  { id: 76, text: "un cunnilingus en tongs", category: "adult" },
  { id: 77, text: "un curé en gogo-dancer sous MDMA", category: "adult" },
  { id: 78, text: "une mamie en cuir qui hurle \"OUI PAPA\"", category: "adult" },
  { id: 79, text: "une diarrhée surprise sur un trampoline", category: "adult" },
  { id: 80, text: "une levrette faite par erreur pendant un câlin", category: "adult" },
  { id: 81, text: "un plug anal en forme de croix catholique", category: "adult" },
  { id: 82, text: "une sucette trempée dans du sperme", category: "adult" },
  { id: 83, text: "un pigeon avec des envies sexuelles suspectes", category: "adult" },
  { id: 84, text: "un poisson rouge accro au BDSM", category: "adult" },
  { id: 85, text: "une érection pendant un enterrement", category: "adult" },
  { id: 86, text: "une fellation interrompue par un tremblement de terre", category: "adult" },
  { id: 87, text: "une veuve qui masturbe un cercueil", category: "adult" },
  { id: 88, text: "des menottes faites de capotes usagées", category: "adult" },
  { id: 89, text: "un vibromasseur contrôlé par la bourse de Tokyo", category: "adult" },
  { id: 90, text: "une main momifiée insérée avec précaution", category: "adult" },
  { id: 91, text: "un phimosis soigné par un exorcisme", category: "adult" },
  { id: 92, text: "un anus illuminé façon guirlande de Noël", category: "adult" },
  { id: 93, text: "un plan à trois avec deux mannequins en plastique", category: "adult" },
  { id: 94, text: "un orgasme à retardement de 48 heures", category: "adult" },
  { id: 95, text: "une croix gammée dessinée en poils pubiens", category: "adult" },
  { id: 96, text: "des règles synchronisées pendant une partouze", category: "adult" },
  { id: 97, text: "une capote remplie de ketchup", category: "adult" },
  { id: 98, text: "une sodomie dans une voiture de police", category: "adult" },
  { id: 99, text: "un cri d'orgasme en morse", category: "adult" },
  { id: 100, text: "un pet chanté en ré mineur", category: "adult" },
  { id: 101, text: "un cercueil qui vibre tout seul", category: "adult" },
  { id: 102, text: "une dinde fourrée de désirs inavoués", category: "adult" },
  { id: 103, text: "un orgasme provoqué par une flûte traversière", category: "adult" },
  { id: 104, text: "un séminaire d'entreprise dans un club échangiste", category: "adult" },
  { id: 105, text: "une sodomie diplomatique entre deux chefs d'État", category: "adult" },
  { id: 106, text: "une poupée gonflable possédée par Karl Marx", category: "adult" },
  { id: 107, text: "une fellation sous hypnose", category: "adult" },
  { id: 108, text: "des crottes de nez dans un sandwich vegan", category: "adult" },
  { id: 109, text: "une levrette au rythme de l'hymne européen", category: "adult" },
  { id: 110, text: "un cunnilingus exécuté par une imprimante 3D", category: "adult" },
  { id: 111, text: "un hamster en latex piloté par télécommande", category: "adult" },
  { id: 112, text: "une partouze déguisée en réunion de famille", category: "adult" },
  { id: 113, text: "un vibromasseur alimenté par des prières", category: "adult" },
  { id: 114, text: "un exorcisme de vagin par téléphone", category: "adult" },
  { id: 115, text: "des tétons qui chantent l'Ave Maria", category: "adult" },
  { id: 116, text: "un préservatif fabriqué à partir de peau de banane", category: "adult" },
  { id: 117, text: "une gifle de bite sous forme de slam poétique", category: "adult" },
  { id: 118, text: "un pet enregistré pour la postérité", category: "adult" },
  { id: 119, text: "une main dans le slip et l'autre dans l'Histoire", category: "adult" },
  { id: 120, text: "une levrette improvisée sur la photocopieuse", category: "adult" },
  { id: 121, text: "une initiation au sexe tantrique avec un hérisson", category: "adult" },
  { id: 122, text: "une fellation dans une bibliothèque municipale", category: "adult" },
  { id: 123, text: "des boules de geisha bénies par le Vatican", category: "adult" },
  { id: 124, text: "un orgasme provoqué par une chorale d'enfants", category: "adult" },
  { id: 125, text: "des testicules huilés sur un autel satanique", category: "adult" },
  { id: 126, text: "une lubrification au beurre de cacahuète", category: "adult" },
  { id: 127, text: "un plan à trois impliquant un évêque, un clown et une chèvre", category: "adult" },
  { id: 128, text: "une partouze en fauteuil roulant sur terrain boueux", category: "adult" },
  { id: 129, text: "un pénis robotisé à commande vocale", category: "adult" },
  { id: 130, text: "une éjaculation à travers un saxophone", category: "adult" },
  { id: 131, text: "une sodomie consentie en réunion Zoom", category: "adult" },
  { id: 132, text: "un orgasme provoqué par une conférence TED", category: "adult" },
  { id: 133, text: "un strip-tease effectué par un jésuite manchot", category: "adult" },
  { id: 134, text: "une chanson paillarde chantée par ton anus", category: "adult" },
  { id: 135, text: "un pet de vierge préservé dans un bocal", category: "adult" },
  { id: 136, text: "un gode rempli de mousse au chocolat", category: "adult" },
  { id: 137, text: "un cunnilingus cosmique sur la face cachée de la Lune", category: "adult" },
  { id: 138, text: "des moignons lubrifiés avec ferveur", category: "adult" },
  { id: 139, text: "un orgasme déclenché par une équation mathématique", category: "adult" },
  { id: 140, text: "un vibromasseur déposé dans un Kinder Surprise", category: "adult" },
  { id: 141, text: "un dildo fabriqué à partir d'os humains", category: "adult" },
  { id: 142, text: "une fellation fantôme pendant ton sommeil", category: "adult" },
  { id: 143, text: "un bukkake en slow motion sur fond de violon triste", category: "adult" },
  { id: 144, text: "une orgie sous hypnose collective", category: "adult" },
  { id: 145, text: "un plan cul qui cite Victor Hugo à chaque coup de rein", category: "adult" },
  { id: 146, text: "une capote en tricot offerte par le Pape", category: "adult" },
  { id: 147, text: "une sodomie avec un extincteur de pompier", category: "adult" },
  { id: 148, text: "une insémination accidentelle par pigeon voyageur", category: "adult" },
  { id: 149, text: "une masturbation partagée par visio en conseil municipal", category: "adult" },
  { id: 150, text: "une fellation donnée en hommage à la République", category: "adult" },
  { id: 151, text: "un orgasme provoqué par la Marseillaise remixée", category: "adult" },
  { id: 152, text: "un sex toy bio-dégradable à base de compost", category: "adult" },
  { id: 153, text: "des jumeaux qui font l'amour par télépathie", category: "adult" },
  { id: 154, text: "une gifle vaginale provoquant un AVC", category: "adult" },
  { id: 155, text: "un cri d'orgasme en latin ecclésiastique", category: "adult" },
  { id: 156, text: "un dildo recyclé en distributeur de bonbons", category: "adult" },
  { id: 157, text: "un cunnilingus effectué en langue des signes", category: "adult" },
  { id: 158, text: "une orgie surprise dans un EHPAD", category: "adult" },
  { id: 159, text: "une sodomie millénaire gravée dans la pierre", category: "adult" },
  { id: 160, text: "une chorale de pets synchronisés", category: "adult" },
  { id: 161, text: "un vibromasseur béni par Bouddha", category: "adult" },
  { id: 162, text: "une fellation éternelle au purgatoire", category: "adult" },
  { id: 163, text: "un bukkake métaphysique dans l'espace-temps", category: "adult" },
  { id: 164, text: "une éjaculation prémonitoire dans un rêve", category: "adult" }
];

export const GAME_PHASES = {
  SETUP: "setup",
  PLAYING: "playing",
  JUDGING: "judging",
  RESULTS: "results",
  ENDED: "ended",
} as const;

export type GamePhase = typeof GAME_PHASES[keyof typeof GAME_PHASES];
