// French card data for the game - 100 Question Cards
export const QUESTION_CARDS = [
  // 1 blank questions (60 cards)
  { id: 1, text: "Mon pire cauchemar ? _____.", blanks: 1, category: "general" },
  { id: 2, text: "Le secret de ma réussite ? _____.", blanks: 1, category: "general" },
  { id: 3, text: "_____ : parfait pour impressionner belle-maman.", blanks: 1, category: "general" },
  { id: 4, text: "Qu'est-ce qui rend _____ si irrésistible ?", blanks: 1, category: "general" },
  { id: 5, text: "Lors de mon dernier rendez-vous galant, j'ai été surpris par _____.", blanks: 1, category: "general" },
  { id: 6, text: "_____ : c'est ce qui manquait à ma vie pour être vraiment pathétique.", blanks: 1, category: "general" },
  { id: 7, text: "La prochaine fois que je vais chez le médecin, je vais lui parler de _____.", blanks: 1, category: "general" },
  { id: 8, text: "Qu'est-ce qui me réveille en pleine nuit ? _____.", blanks: 1, category: "general" },
  { id: 9, text: "Mon talent caché ? _____.", blanks: 1, category: "general" },
  { id: 10, text: "Ce qui me donne de l'espoir pour l'humanité : _____.", blanks: 1, category: "general" },
  { id: 11, text: "Ma plus grande peur irrationnelle : _____.", blanks: 1, category: "general" },
  { id: 12, text: "Ce que je ferais si j'étais invisible : _____.", blanks: 1, category: "general" },
  { id: 13, text: "Mon superpouvoir secret : _____.", blanks: 1, category: "general" },
  { id: 14, text: "Ce qui me rend fou de rage : _____.", blanks: 1, category: "general" },
  { id: 15, text: "Mon addiction secrète : _____.", blanks: 1, category: "general" },
  { id: 16, text: "Ce que je cache dans mon tiroir secret : _____.", blanks: 1, category: "general" },
  { id: 17, text: "Ma plus grande honte : _____.", blanks: 1, category: "general" },
  { id: 18, text: "Ce qui me console quand je suis triste : _____.", blanks: 1, category: "general" },
  { id: 19, text: "Mon obsession du moment : _____.", blanks: 1, category: "general" },
  { id: 20, text: "Ce que je fais quand personne ne me regarde : _____.", blanks: 1, category: "general" },
  { id: 21, text: "Mon plan pour conquérir le monde : _____.", blanks: 1, category: "general" },
  { id: 22, text: "Ce qui me fait fondre : _____.", blanks: 1, category: "general" },
  { id: 23, text: "Mon excuse préférée : _____.", blanks: 1, category: "general" },
  { id: 24, text: "Ce que je collectionne en secret : _____.", blanks: 1, category: "general" },
  { id: 25, text: "Ma théorie du complot favorite : _____.", blanks: 1, category: "general" },
  { id: 26, text: "Ce qui me ferait pleurer de joie : _____.", blanks: 1, category: "general" },
  { id: 27, text: "Mon rituel du matin : _____.", blanks: 1, category: "general" },
  { id: 28, text: "Ce que je dis dans mes rêves : _____.", blanks: 1, category: "general" },
  { id: 29, text: "Mon péché mignon : _____.", blanks: 1, category: "general" },
  { id: 30, text: "Ce qui me donne des frissons : _____.", blanks: 1, category: "general" },
  { id: 31, text: "Mon mensonge préféré : _____.", blanks: 1, category: "general" },
  { id: 32, text: "Ce que je ferais pour un million d'euros : _____.", blanks: 1, category: "general" },
  { id: 33, text: "Mon fantasme inavouable : _____.", blanks: 1, category: "general" },
  { id: 34, text: "Ce qui me fait rougir : _____.", blanks: 1, category: "general" },
  { id: 35, text: "Mon remède miracle contre l'ennui : _____.", blanks: 1, category: "general" },
  { id: 36, text: "Ce que je ne devrais jamais faire en public : _____.", blanks: 1, category: "general" },
  { id: 37, text: "Mon plus gros regret : _____.", blanks: 1, category: "general" },
  { id: 38, text: "Ce qui me fait passer pour un fou : _____.", blanks: 1, category: "general" },
  { id: 39, text: "Mon vice secret : _____.", blanks: 1, category: "general" },
  { id: 40, text: "Ce que je ferais si j'étais président : _____.", blanks: 1, category: "general" },
  { id: 41, text: "Mon plus grand accomplissement : _____.", blanks: 1, category: "general" },
  { id: 42, text: "Ce qui me rend ridicule : _____.", blanks: 1, category: "general" },
  { id: 43, text: "Ma philosophie de vie : _____.", blanks: 1, category: "general" },
  { id: 44, text: "Ce que j'emporterais sur une île déserte : _____.", blanks: 1, category: "general" },
  { id: 45, text: "Mon moment le plus gênant : _____.", blanks: 1, category: "general" },
  { id: 46, text: "Ce qui me fait perdre la tête : _____.", blanks: 1, category: "general" },
  { id: 47, text: "Mon rêve le plus fou : _____.", blanks: 1, category: "general" },
  { id: 48, text: "Ce que je fais quand je m'ennuie : _____.", blanks: 1, category: "general" },
  { id: 49, text: "Mon déguisement préféré : _____.", blanks: 1, category: "general" },
  { id: 50, text: "Ce qui me fait peur la nuit : _____.", blanks: 1, category: "general" },
  { id: 51, text: "Mon animal spirituel : _____.", blanks: 1, category: "general" },
  { id: 52, text: "Ce que je mange en cachette : _____.", blanks: 1, category: "general" },
  { id: 53, text: "Mon habitude la plus bizarre : _____.", blanks: 1, category: "general" },
  { id: 54, text: "Ce qui me fait sourire bêtement : _____.", blanks: 1, category: "general" },
  { id: 55, text: "Mon invention révolutionnaire : _____.", blanks: 1, category: "general" },
  { id: 56, text: "Ce que je fais sous la douche : _____.", blanks: 1, category: "general" },
  { id: 57, text: "Mon plus grand mystère : _____.", blanks: 1, category: "general" },
  { id: 58, text: "Ce qui me donne envie de danser : _____.", blanks: 1, category: "general" },
  { id: 59, text: "Mon excuse la plus créative : _____.", blanks: 1, category: "general" },
  { id: 60, text: "Ce qui me ferait changer de vie : _____.", blanks: 1, category: "general" },
  
  // 2 blanks questions (40 cards)
  { id: 61, text: "La chose la plus embarrassante que j'ai faite pour _____ c'est _____.", blanks: 2, category: "general" },
  { id: 62, text: "_____ + _____ = le combo parfait pour ruiner une soirée.", blanks: 2, category: "general" },
  { id: 63, text: "Maman, pourquoi il y a _____ dans mon _____ ?", blanks: 2, category: "general" },
  { id: 64, text: "Comment j'ai découvert que _____ et _____ ne font pas bon ménage.", blanks: 2, category: "general" },
  { id: 65, text: "Hier soir, j'ai rêvé de _____ qui dansait avec _____.", blanks: 2, category: "general" },
  { id: 66, text: "Mon secret pour mélanger _____ et _____ : ne jamais le faire.", blanks: 2, category: "general" },
  { id: 67, text: "Quand je vois _____, je pense immédiatement à _____.", blanks: 2, category: "general" },
  { id: 68, text: "_____ était bien, mais _____ c'est encore mieux.", blanks: 2, category: "general" },
  { id: 69, text: "Je préfère _____ le matin et _____ le soir.", blanks: 2, category: "general" },
  { id: 70, text: "La recette du bonheur : prenez _____, ajoutez _____.", blanks: 2, category: "general" },
  { id: 71, text: "Si je devais choisir entre _____ et _____, je prendrais les deux.", blanks: 2, category: "general" },
  { id: 72, text: "Mon pire date : _____ qui parle de _____ pendant 3 heures.", blanks: 2, category: "general" },
  { id: 73, text: "_____ c'est bien, mais avec _____ c'est magique.", blanks: 2, category: "general" },
  { id: 74, text: "J'ai essayé de mélanger _____ et _____, maintenant je suis interdit de séjour.", blanks: 2, category: "general" },
  { id: 75, text: "Le secret de ma grand-mère : remplacer _____ par _____.", blanks: 2, category: "general" },
  { id: 76, text: "_____ le lundi, _____ le vendredi, c'est ma semaine type.", blanks: 2, category: "general" },
  { id: 77, text: "Docteur, c'est normal d'avoir _____ quand je vois _____ ?", blanks: 2, category: "general" },
  { id: 78, text: "_____ + _____ = ma nouvelle passion secrète.", blanks: 2, category: "general" },
  { id: 79, text: "Pour séduire, il faut _____ et surtout éviter _____.", blanks: 2, category: "general" },
  { id: 80, text: "_____ c'est fini, maintenant c'est l'époque de _____.", blanks: 2, category: "general" },
  { id: 81, text: "Mon plan B : si _____ ne marche pas, j'essaie _____.", blanks: 2, category: "general" },
  { id: 82, text: "_____ au petit-déjeuner et _____ au dîner, je vis dangereusement.", blanks: 2, category: "general" },
  { id: 83, text: "Ma thérapie : remplacer _____ par _____ dans ma vie.", blanks: 2, category: "general" },
  { id: 84, text: "_____ me rappelle toujours _____.", blanks: 2, category: "general" },
  { id: 85, text: "Pour impressionner mes amis, je mélange _____ et _____.", blanks: 2, category: "general" },
  { id: 86, text: "_____ le jour, _____ la nuit, c'est ma double vie.", blanks: 2, category: "general" },
  { id: 87, text: "Si j'étais un super-héros, mon pouvoir serait de transformer _____ en _____.", blanks: 2, category: "general" },
  { id: 88, text: "_____ et _____ : le duo qui a changé ma vie.", blanks: 2, category: "general" },
  { id: 89, text: "Ma plus grande découverte : _____ va parfaitement avec _____.", blanks: 2, category: "general" },
  { id: 90, text: "_____ me fait penser à _____, et ça me dérange.", blanks: 2, category: "general" },
  { id: 91, text: "Pour me consoler, je prends _____ et j'ajoute _____.", blanks: 2, category: "general" },
  { id: 92, text: "_____ c'était avant, maintenant j'ai découvert _____.", blanks: 2, category: "general" },
  { id: 93, text: "Mon cocktail secret : _____ mélangé à _____.", blanks: 2, category: "general" },
  { id: 94, text: "_____ me rend fou, mais _____ me calme.", blanks: 2, category: "general" },
  { id: 95, text: "Ma routine matinale : _____ puis _____.", blanks: 2, category: "general" },
  { id: 96, text: "_____ et _____ : mes deux plus grandes passions.", blanks: 2, category: "general" },
  { id: 97, text: "Pour survivre à cette journée, j'ai besoin de _____ et de _____.", blanks: 2, category: "general" },
  { id: 98, text: "_____ me rappelle pourquoi j'adore _____.", blanks: 2, category: "general" },
  { id: 99, text: "Ma recette du désastre : prenez _____, mélangez avec _____.", blanks: 2, category: "general" },
  { id: 100, text: "_____ et _____ : le couple que personne n'avait vu venir.", blanks: 2, category: "general" }
];

// French Answer Cards - 300 cards total
export const ANSWER_CARDS = [
  // Humor & Absurd (100 cards)
  { id: 1, text: "de l'argent et ma dignité", category: "general" },
  { id: 2, text: "mes économies", category: "general" },
  { id: 3, text: "un pingouin unijambiste", category: "general" },
  { id: 4, text: "pleurer en position fœtale", category: "general" },
  { id: 5, text: "ma belle-mère en maillot de bain", category: "general" },
  { id: 6, text: "une vidéo YouTube qui dure 3 heures", category: "general" },
  { id: 7, text: "faire semblant d'être un expert", category: "general" },
  { id: 8, text: "des chaussettes sales", category: "general" },
  { id: 9, text: "mon ex en réunion Zoom", category: "general" },
  { id: 10, text: "un sandwich au nutella périmé", category: "general" },
  { id: 11, text: "danser nu devant mon miroir", category: "general" },
  { id: 12, text: "mes photos de profil Tinder", category: "general" },
  { id: 13, text: "un cours de yoga pour chats", category: "general" },
  { id: 14, text: "mes recherches Google à 3h du matin", category: "general" },
  { id: 15, text: "mon patron en slip de bain", category: "general" },
  { id: 16, text: "une collection de figurines de licornes", category: "general" },
  { id: 17, text: "des tacos qui se battent", category: "general" },
  { id: 18, text: "une licorne dépressive", category: "general" },
  { id: 19, text: "des pâtes qui parlent", category: "general" },
  { id: 20, text: "le WiFi de ma grand-mère", category: "general" },
  { id: 21, text: "un chat en costard", category: "general" },
  { id: 22, text: "ma dignité perdue", category: "general" },
  { id: 23, text: "des chaussettes qui sentent le fromage", category: "general" },
  { id: 24, text: "une moustache de hipster", category: "general" },
  { id: 25, text: "mon ex qui mange des céréales", category: "general" },
  { id: 26, text: "un tatouage de ma grand-mère", category: "general" },
  { id: 27, text: "pleurer en regardant des vidéos de chatons", category: "general" },
  { id: 28, text: "mon historique de recherche Google", category: "general" },
  { id: 29, text: "une passion secrète pour les romans à l'eau de rose", category: "general" },
  { id: 30, text: "mentionner mon ex 47 fois pendant le repas", category: "general" },
  { id: 31, text: "un hamster qui fait du crossfit", category: "general" },
  { id: 32, text: "mes rêves brisés et du chocolat", category: "general" },
  { id: 33, text: "une armée de canards en colère", category: "general" },
  { id: 34, text: "danser la salsa avec une chaussure", category: "general" },
  { id: 35, text: "mes selfies ratés", category: "general" },
  { id: 36, text: "un concours de pets silencieux", category: "general" },
  { id: 37, text: "mon voisin qui tond sa pelouse à 6h", category: "general" },
  { id: 38, text: "une pizza qui juge mes choix de vie", category: "general" },
  { id: 39, text: "mes tentatives de cuisine", category: "general" },
  { id: 40, text: "un documentaire sur les escargots ninja", category: "general" },
  { id: 41, text: "mes messages vocaux de 10 minutes", category: "general" },
  { id: 42, text: "une chaussette orpheline", category: "general" },
  { id: 43, text: "mon addiction aux séries Netflix", category: "general" },
  { id: 44, text: "un concours de regard avec mon chat", category: "general" },
  { id: 45, text: "mes excuses créatives pour éviter le sport", category: "general" },
  { id: 46, text: "une licorne qui fait de la comptabilité", category: "general" },
  { id: 47, text: "mes discussions philosophiques avec mon frigo", category: "general" },
  { id: 48, text: "un pingouin qui vend des assurances", category: "general" },
  { id: 49, text: "mes talents cachés de mime", category: "general" },
  { id: 50, text: "une machine à café rebelle", category: "general" },
  { id: 51, text: "mes tentatives de séduction ratées", category: "general" },
  { id: 52, text: "un cours de salsa pour robots", category: "general" },
  { id: 53, text: "ma collection secrète de memes", category: "general" },
  { id: 54, text: "un débat avec ma plante verte", category: "general" },
  { id: 55, text: "mes chorégraphies sous la douche", category: "general" },
  { id: 56, text: "un koala qui fait du stand-up", category: "general" },
  { id: 57, text: "mes théories du complot sur les chaussettes", category: "general" },
  { id: 58, text: "une armée de fourmis organisées", category: "general" },
  { id: 59, text: "mes résolutions abandonnées", category: "general" },
  { id: 60, text: "un concours de beauté pour légumes", category: "general" },
  { id: 61, text: "mes conversations avec Siri", category: "general" },
  { id: 62, text: "un éléphant qui fait du tricot", category: "general" },
  { id: 63, text: "mes rituels matinaux bizarres", category: "general" },
  { id: 64, text: "une invasion de canards en plastique", category: "general" },
  { id: 65, text: "mes tentatives de méditation", category: "general" },
  { id: 66, text: "un concours de grimaces professionnelles", category: "general" },
  { id: 67, text: "mes playlists embarrassantes", category: "general" },
  { id: 68, text: "une bataille épique entre deux oreillers", category: "general" },
  { id: 69, text: "mes excuses pour éviter les réunions", category: "general" },
  { id: 70, text: "un laboratoire secret de chaussettes", category: "general" },
  { id: 71, text: "mes danses de victoire secrètes", category: "general" },
  { id: 72, text: "une convention de licornes dépressives", category: "general" },
  { id: 73, text: "mes tentatives de jardinage", category: "general" },
  { id: 74, text: "un club de lecture pour poissons rouges", category: "general" },
  { id: 75, text: "mes stratégies d'évitement social", category: "general" },
  { id: 76, text: "une machine qui traduit les miaulements", category: "general" },
  { id: 77, text: "mes talents de procrastination", category: "general" },
  { id: 78, text: "un concours de bâillements synchronisés", category: "general" },
  { id: 79, text: "mes techniques de fuite face aux responsabilités", category: "general" },
  { id: 80, text: "une armée de robots aspirateurs rebelles", category: "general" },
  { id: 81, text: "mes monologues devant le miroir", category: "general" },
  { id: 82, text: "un festival de pets de licornes", category: "general" },
  { id: 83, text: "mes excuses pour manger du chocolat", category: "general" },
  { id: 84, text: "une bataille de coussins intergalactique", category: "general" },
  { id: 85, text: "mes tentatives de rangement", category: "general" },
  { id: 86, text: "un dinosaure qui fait du yoga", category: "general" },
  { id: 87, text: "mes discussions avec mon reflet", category: "general" },
  { id: 88, text: "une compétition de siestes professionnelles", category: "general" },
  { id: 89, text: "mes théories sur la disparition des chaussettes", category: "general" },
  { id: 90, text: "un laboratoire de fabrication de rêves", category: "general" },
  { id: 91, text: "mes tentatives de cuisine créative", category: "general" },
  { id: 92, text: "une école de danse pour escargots", category: "general" },
  { id: 93, text: "mes stratégies pour éviter les lundis", category: "general" },
  { id: 94, text: "un concours de ronflements mélodieux", category: "general" },
  { id: 95, text: "mes talents cachés de ventriloque", category: "general" },
  { id: 96, text: "une invasion de post-it vengeurs", category: "general" },
  { id: 97, text: "mes rituels pour invoquer le week-end", category: "general" },
  { id: 98, text: "un débat philosophique avec mon oreiller", category: "general" },
  { id: 99, text: "mes excuses créatives pour rester au lit", category: "general" },
  { id: 100, text: "une machine à fabriquer des excuses", category: "general" },

  // Relationships & Social (100 cards)
  { id: 101, text: "mes parents qui découvrent mon historique de navigation", category: "general" },
  { id: 102, text: "un rendez-vous Tinder qui se passe mal", category: "general" },
  { id: 103, text: "expliquer TikTok à ma grand-mère", category: "general" },
  { id: 104, text: "mes amis qui découvrent mes photos de lycée", category: "general" },
  { id: 105, text: "un dîner de famille qui dérape", category: "general" },
  { id: 106, text: "mes voisins bruyants", category: "general" },
  { id: 107, text: "mon coiffeur qui ne comprend jamais ce que je veux", category: "general" },
  { id: 108, text: "mes collègues en réunion Zoom", category: "general" },
  { id: 109, text: "ma grand-mère sur Facebook", category: "general" },
  { id: 110, text: "un ami qui emprunte tout et ne rend jamais rien", category: "general" },
  { id: 111, text: "mes parents qui essaient d'être cool", category: "general" },
  { id: 112, text: "un ex qui commente toutes mes photos", category: "general" },
  { id: 113, text: "mes amis qui jugent mes choix Netflix", category: "general" },
  { id: 114, text: "un rendez-vous qui parle que de son ex", category: "general" },
  { id: 115, text: "ma mère qui veut me présenter quelqu'un", category: "general" },
  { id: 116, text: "mes amis qui spoilent les séries", category: "general" },
  { id: 117, text: "un voisin qui emprunte du sucre depuis 3 ans", category: "general" },
  { id: 118, text: "mes collègues qui mangent fort", category: "general" },
  { id: 119, text: "un ami qui ne comprend jamais les blagues", category: "general" },
  { id: 120, text: "ma famille qui commente mon célibat", category: "general" },
  { id: 121, text: "un rendez-vous qui arrive en retard de 2 heures", category: "general" },
  { id: 122, text: "mes amis qui postent leurs vacances", category: "general" },
  { id: 123, text: "un collègue qui chante faux", category: "general" },
  { id: 124, text: "ma grand-mère qui apprend l'argot", category: "general" },
  { id: 125, text: "mes parents qui découvrent les memes", category: "general" },
  { id: 126, text: "un ami qui fait du MLM", category: "general" },
  { id: 127, text: "mes voisins qui font la fête un mardi", category: "general" },
  { id: 128, text: "un ex qui devient célèbre", category: "general" },
  { id: 129, text: "ma famille sur WhatsApp", category: "general" },
  { id: 130, text: "un ami qui ne paie jamais au restaurant", category: "general" },
  { id: 131, text: "mes collègues qui mangent mon déjeuner", category: "general" },
  { id: 132, text: "un rendez-vous qui vit encore chez ses parents", category: "general" },
  { id: 133, text: "ma mère qui likе toutes mes photos", category: "general" },
  { id: 134, text: "mes amis qui arrivent en retard", category: "general" },
  { id: 135, text: "un voisin qui tond sa pelouse à 6h", category: "general" },
  { id: 136, text: "mes parents qui essaient les nouvelles technologies", category: "general" },
  { id: 137, text: "un ex qui sort avec mon ami", category: "general" },
  { id: 138, text: "ma famille qui organise des jeux après le repas", category: "general" },
  { id: 139, text: "un collègue qui parle fort au téléphone", category: "general" },
  { id: 140, text: "mes amis qui commandent toujours la même chose", category: "general" },
  { id: 141, text: "un rendez-vous qui ne ressemble pas à ses photos", category: "general" },
  { id: 142, text: "ma grand-mère qui découvre Instagram", category: "general" },
  { id: 143, text: "mes voisins qui déménagent un dimanche", category: "general" },
  { id: 144, text: "un ami qui raconte toujours les mêmes histoires", category: "general" },
  { id: 145, text: "mes parents qui veulent être amis sur Facebook", category: "general" },
  { id: 146, text: "un ex qui garde mes affaires", category: "general" },
  { id: 147, text: "ma famille qui pose des questions gênantes", category: "general" },
  { id: 148, text: "un collègue qui sent fort", category: "general" },
  { id: 149, text: "mes amis qui me demandent de l'argent", category: "general" },
  { id: 150, text: "un rendez-vous qui ne met pas de déodorant", category: "general" },
  { id: 151, text: "ma mère qui fait des commentaires sur mon poids", category: "general" },
  { id: 152, text: "mes voisins qui écoutent de la musique forte", category: "general" },
  { id: 153, text: "un ami qui ne rend jamais les livres", category: "general" },
  { id: 154, text: "mes parents qui me donnent des conseils de vie", category: "general" },
  { id: 155, text: "un ex qui refait surface à 2h du matin", category: "general" },
  { id: 156, text: "ma famille qui organise des réunions Zoom", category: "general" },
  { id: 157, text: "un collègue qui microgère tout", category: "general" },
  { id: 158, text: "mes amis qui ne répondent jamais aux messages", category: "general" },
  { id: 159, text: "un rendez-vous qui parle de cryptomonnaies", category: "general" },
  { id: 160, text: "ma grand-mère qui apprend les emojis", category: "general" },
  { id: 161, text: "mes voisins qui se disputent", category: "general" },
  { id: 162, text: "un ami qui spoile les films", category: "general" },
  { id: 163, text: "mes parents qui essaient d'être branchés", category: "general" },
  { id: 164, text: "un ex qui devient mon patron", category: "general" },
  { id: 165, text: "ma famille qui critique mes choix", category: "general" },
  { id: 166, text: "un collègue qui mange mes yaourts", category: "general" },
  { id: 167, text: "mes amis qui annulent au dernier moment", category: "general" },
  { id: 168, text: "un rendez-vous qui ne paie pas", category: "general" },
  { id: 169, text: "ma mère qui partage des fake news", category: "general" },
  { id: 170, text: "mes voisins qui regardent par la fenêtre", category: "general" },
  { id: 171, text: "un ami qui donne son avis sur tout", category: "general" },
  { id: 172, text: "mes parents qui découvrent YouTube", category: "general" },
  { id: 173, text: "un ex qui se marie", category: "general" },
  { id: 174, text: "ma famille qui organise des vacances ensemble", category: "general" },
  { id: 175, text: "un collègue qui raconte sa vie", category: "general" },
  { id: 176, text: "mes amis qui me posent des lapins", category: "general" },
  { id: 177, text: "un rendez-vous qui regarde son téléphone", category: "general" },
  { id: 178, text: "ma grand-mère qui apprend à conduire", category: "general" },
  { id: 179, text: "mes voisins qui font des travaux", category: "general" },
  { id: 180, text: "un ami qui critique mes goûts musicaux", category: "general" },
  { id: 181, text: "mes parents qui s'inquiètent pour tout", category: "general" },
  { id: 182, text: "un ex qui devient influenceur", category: "general" },
  { id: 183, text: "ma famille qui me fait du chantage affectif", category: "general" },
  { id: 184, text: "un collègue qui respire fort", category: "general" },
  { id: 185, text: "mes amis qui me jugent sur mes séries", category: "general" },
  { id: 186, text: "un rendez-vous qui parle de son régime", category: "general" },
  { id: 187, text: "ma mère qui veut refaire ma décoration", category: "general" },
  { id: 188, text: "mes voisins qui organisent des barbecues", category: "general" },
  { id: 189, text: "un ami qui emprunte ma voiture", category: "general" },
  { id: 190, text: "mes parents qui me demandent des petits-enfants", category: "general" },
  { id: 191, text: "un ex qui sort avec quelqu'un de plus jeune", category: "general" },
  { id: 192, text: "ma famille qui critique mes cheveux", category: "general" },
  { id: 193, text: "un collègue qui mange avec les doigts", category: "general" },
  { id: 194, text: "mes amis qui oublient mon anniversaire", category: "general" },
  { id: 195, text: "un rendez-vous qui vit avec ses 5 chats", category: "general" },
  { id: 196, text: "ma grand-mère qui apprend le rap", category: "general" },
  { id: 197, text: "mes voisins qui jardinent à 7h", category: "general" },
  { id: 198, text: "un ami qui ne comprend pas l'ironie", category: "general" },
  { id: 199, text: "mes parents qui me surveillent sur les réseaux", category: "general" },
  { id: 200, text: "un ex qui demande de l'argent", category: "general" },

  // Modern Life & Technology (100 cards)
  { id: 201, text: "mon téléphone qui bug au pire moment", category: "general" },
  { id: 202, text: "Netflix qui me juge sur mes choix", category: "general" },
  { id: 203, text: "mon ordinateur qui plante pendant un examen", category: "general" },
  { id: 204, text: "Alexa qui m'ignore", category: "general" },
  { id: 205, text: "mon GPS qui me perd", category: "general" },
  { id: 206, text: "Instagram qui supprime mes photos", category: "general" },
  { id: 207, text: "mon wifi qui coupe pendant une réunion", category: "general" },
  { id: 208, text: "TikTok qui connaît mes secrets", category: "general" },
  { id: 209, text: "mon autocorrecteur qui me trahit", category: "general" },
  { id: 210, text: "YouTube qui me recommande des vidéos bizarres", category: "general" },
  { id: 211, text: "mon réveil qui ne sonne pas", category: "general" },
  { id: 212, text: "Spotify qui joue de la musique déprimante", category: "general" },
  { id: 213, text: "mon code wifi que j'ai oublié", category: "general" },
  { id: 214, text: "Google qui autocomplete mes recherches gênantes", category: "general" },
  { id: 215, text: "mon téléphone qui tombe dans les toilettes", category: "general" },
  { id: 216, text: "Facebook qui me rappelle mes ex", category: "general" },
  { id: 217, text: "mon ordinateur qui met à jour au mauvais moment", category: "general" },
  { id: 218, text: "Siri qui ne comprend pas mon accent", category: "general" },
  { id: 219, text: "mon imprimante qui refuse de fonctionner", category: "general" },
  { id: 220, text: "Twitter qui limite mes caractères", category: "general" },
  { id: 221, text: "mon email qui part avant d'être fini", category: "general" },
  { id: 222, text: "Zoom qui coupe ma vidéo", category: "general" },
  { id: 223, text: "mon mot de passe que j'ai oublié", category: "general" },
  { id: 224, text: "WhatsApp qui envoie mes messages à la mauvaise personne", category: "general" },
  { id: 225, text: "mon téléphone qui s'éteint à 1% de batterie", category: "general" },
  { id: 226, text: "Amazon qui me suggère des achats embarrassants", category: "general" },
  { id: 227, text: "mon cloud qui synchronise mes photos bizarres", category: "general" },
  { id: 228, text: "Discord qui me déconnecte pendant un jeu", category: "general" },
  { id: 229, text: "mon clavier qui écrit tout en majuscules", category: "general" },
  { id: 230, text: "LinkedIn qui me propose des jobs ridicules", category: "general" },
  { id: 231, text: "mon navigateur qui plante sur un site important", category: "general" },
  { id: 232, text: "Uber qui me fait attendre 45 minutes", category: "general" },
  { id: 233, text: "mon antivirus qui trouve des virus imaginaires", category: "general" },
  { id: 234, text: "Pinterest qui me montre ce que je ne peux pas me payer", category: "general" },
  { id: 235, text: "mon backup qui ne fonctionne pas", category: "general" },
  { id: 236, text: "Tinder qui me match avec mon cousin", category: "general" },
  { id: 237, text: "mon VPN qui me géolocalise en Moldavie", category: "general" },
  { id: 238, text: "Reddit qui me fait perdre 6 heures", category: "general" },
  { id: 239, text: "mon stockage qui est plein", category: "general" },
  { id: 240, text: "Twitch qui lag pendant le moment important", category: "general" },
  { id: 241, text: "mon écran qui se fige", category: "general" },
  { id: 242, text: "PayPal qui bloque mon compte", category: "general" },
  { id: 243, text: "mon micro qui grésille", category: "general" },
  { id: 244, text: "Steam qui télécharge une mise à jour de 50 Go", category: "general" },
  { id: 245, text: "ma webcam qui s'allume toute seule", category: "general" },
  { id: 246, text: "Netflix qui retire ma série préférée", category: "general" },
  { id: 247, text: "mon chargeur qui ne marche plus", category: "general" },
  { id: 248, text: "Instagram qui change encore l'algorithme", category: "general" },
  { id: 249, text: "mon écran tactile qui ne répond plus", category: "general" },
  { id: 250, text: "Snapchat qui sauvegarde mes photos moches", category: "general" },
  { id: 251, text: "mon casque qui fait des grésillements", category: "general" },
  { id: 252, text: "TikTok qui me montre mes vidéos de 2020", category: "general" },
  { id: 253, text: "mon ordinateur qui ventile comme un avion", category: "general" },
  { id: 254, text: "Teams qui m'affiche en mode patate", category: "general" },
  { id: 255, text: "mon téléphone qui vibre dans ma poche fantôme", category: "general" },
  { id: 256, text: "YouTube qui met de la pub au moment crucial", category: "general" },
  { id: 257, text: "mon clavier qui colle", category: "general" },
  { id: 258, text: "Spotify qui joue de la pub de parfum", category: "general" },
  { id: 259, text: "mon écran qui a une ligne de pixels morts", category: "general" },
  { id: 260, text: "Facebook qui me suggère des amis bizarres", category: "general" },
  { id: 261, text: "mon téléphone qui surchauffe", category: "general" },
  { id: 262, text: "Google Maps qui me fait faire des détours", category: "general" },
  { id: 263, text: "mon app bancaire qui refuse ma connexion", category: "general" },
  { id: 264, text: "Twitter qui me montre des tweets de 2012", category: "general" },
  { id: 265, text: "mon disque dur qui fait du bruit", category: "general" },
  { id: 266, text: "Zoom qui active mon micro sans prévenir", category: "general" },
  { id: 267, text: "mon téléphone qui appelle tout seul", category: "general" },
  { id: 268, text: "Netflix qui me demande si je regarde toujours", category: "general" },
  { id: 269, text: "mon ordinateur qui redémarre tout seul", category: "general" },
  { id: 270, text: "Instagram qui cache mes stories", category: "general" },
  { id: 271, text: "mon bluetooth qui se connecte au mauvais appareil", category: "general" },
  { id: 272, text: "WhatsApp qui affiche mes messages comme lus", category: "general" },
  { id: 273, text: "mon écran qui a des taches", category: "general" },
  { id: 274, text: "YouTube qui retire le son de mes vidéos", category: "general" },
  { id: 275, text: "mon téléphone qui ne reconnait plus mon visage", category: "general" },
  { id: 276, text: "Spotify qui mélange ma playlist zen avec du métal", category: "general" },
  { id: 277, text: "mon wifi qui se connecte mais sans internet", category: "general" },
  { id: 278, text: "TikTok qui me montre des danses que je ne comprends pas", category: "general" },
  { id: 279, text: "mon ordinateur qui affiche l'écran bleu de la mort", category: "general" },
  { id: 280, text: "Amazon qui livre mon colis au voisin", category: "general" },
  { id: 281, text: "mon autocorrecteur qui change ducoup en canard", category: "general" },
  { id: 282, text: "Google qui me demande si je suis un robot", category: "general" },
  { id: 283, text: "mon téléphone qui vibre pour rien", category: "general" },
  { id: 284, text: "Netflix qui enlève les sous-titres", category: "general" },
  { id: 285, text: "mon ordinateur qui fait 50 bruits au démarrage", category: "general" },
  { id: 286, text: "Instagram qui compresse mes photos", category: "general" },
  { id: 287, text: "mon GPS qui parle en chinois", category: "general" },
  { id: 288, text: "Zoom qui inverse ma caméra", category: "general" },
  { id: 289, text: "mon téléphone qui prend des photos dans ma poche", category: "general" },
  { id: 290, text: "YouTube qui me recommande mes propres vidéos", category: "general" },
  { id: 291, text: "mon ordinateur qui s'éteint pendant une sauvegarde", category: "general" },
  { id: 292, text: "Spotify qui joue la même chanson en boucle", category: "general" },
  { id: 293, text: "mon email qui classe tout en spam", category: "general" },
  { id: 294, text: "TikTok qui supprime mes vidéos virales", category: "general" },
  { id: 295, text: "mon téléphone qui refuse de se charger", category: "general" },
  { id: 296, text: "Google qui corrige mes fautes avec d'autres fautes", category: "general" },
  { id: 297, text: "mon ordinateur qui lag pendant les jeux", category: "general" },
  { id: 298, text: "Netflix qui spoile la fin dans la miniature", category: "general" },
  { id: 299, text: "mon téléphone qui s'allume tout seul la nuit", category: "general" },
  { id: 300, text: "Alexa qui commande 50 rouleaux de papier toilette", category: "general" }
];

export const GAME_PHASES = {
  SETUP: "setup",
  PLAYING: "playing",
  JUDGING: "judging",
  RESULTS: "results",
  ENDED: "ended",
} as const;

export type GamePhase = typeof GAME_PHASES[keyof typeof GAME_PHASES];
